# basic options
title: Your awesome title
author: Siddharth Tourani
email: your-email@domain.com
description: A wonderful site
github_username: siddharthtourani

# Build Settings
markdown: kramdown
theme: minima
