# basic options
title: Your awesome title
author: Siddharth Tourani
email: siddharth.tourani@iwr.uni-heidelberg.de
description: A wonderful site
github_username: siddharthtourani

# Build Settings
markdown: kramdown
theme: minima
